name: latihan_soal
version: 1.0.0+1
publish_to: none
description: Aplikasi Latihan Soal SMA.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  flutter: 
    sdk: flutter
  profil_siswa:
    path: ../profil_siswa
  chat_page:
    path: ../chat_page
  konst_variabel:
    path: ../konst_variabel
  extended_image: ^6.3.2
  dio: ^4.0.6
  google_sign_in: ^5.4.2
  dropdown_search: ^5.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter 

flutter: 
  assets: 
    - assets/logo/
    - assets/pelajaran/
  uses-material-design: true

